#+title: Survival Common Lisp - Code Examples
#+author: conao3

[[https://github.com/conao3/book-survival-common-lisp][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/book-survival-common-lisp.png]]

[[https://github.com/conao3/book-survival-common-lisp/blob/master/LICENSE][https://img.shields.io/github/license/conao3/book-survival-common-lisp.svg?style=flat-square]]
[[https://github.com/conao3/book-survival-common-lisp/releases][https://img.shields.io/github/tag/conao3/book-survival-common-lisp.svg?style=flat-square]]

* About

This repository contains practical code examples and snippets for the book "Survival Common Lisp". Each section corresponds to a chapter in the book, providing hands-on exercises and working implementations you can run locally.

* Prerequisites

- [[https://github.com/roswell/roswell][Roswell]] - A Common Lisp implementation manager and launcher

* Project Structure

| Directory  | Description                                     |
|------------+-------------------------------------------------|
| section1/  | Roswell basics - installation, scripts, builds  |
| section2/  | Lem editor setup and usage                      |
| section3/  | Building a postal code lookup application       |
| section4/  | Extending the postal code application           |
| section5/  | Web application development                     |

* Getting Started

Install Roswell and SBCL:

#+begin_src shell
pacman -S roswell-git   # or your package manager equivalent
ros install sbcl-bin
#+end_src

Add Roswell binaries to your PATH:

#+begin_src shell
export PATH=$HOME/.roswell/bin:$PATH
#+end_src

Navigate to any section directory and follow the README for that chapter.

* Example: Running a Roswell Script

#+begin_src shell
cd section1
ros fact.ros 10
# => Factorial 10 = 3628800
#+end_src

* Contributing

Contributions are welcome. Feel free to open issues for questions or submit pull requests for improvements.

* License

MIT License - Copyright (c) Naoya Yamashita

See [[https://github.com/conao3/book-survival-common-lisp/blob/master/LICENSE][LICENSE]] for details.

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
